appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: ygiwmWWJoXtuSfrhuv3d4TQhuUek/AzW8Gc7MI+1CLpd2mZe4RPCPBT29AE8u1bczbJxbQPk+Thz4/QlG8D1X1jlnfU708Trg8nyzQnCdAds8zlJ877lRj071es+2U32uCMp19B6QWl4nwMGneXy3nTDXu5jbj/CEk5uZErS6GPpM73tJL9/IcUFc9nJ+mi179e41v7Wzf5ZZJrvao1dsNfCrCEx80psWyB79v26oQ452oPaLaLmdDWEJqKkqE7GLxV+HKHpGsyBrntRDAX/qHdYfwxOsg2nFyCJOx4fsPh9UBBMXV54YildFH83SrLk5FUtN8a3SJTsyWNlV+TrVRSXuZIOnlIFWn/XrxXLteZiudtPUHYWiFAVOOLImegWc0jJF/Kd78oeMAsnJOc9DF+lgj7J0/zDwxHsMVAAczufIL3bD1RKdalrZ50HITBKkOzrqyP71MMGYwr0VIA00vcKSDKBEx2CUR4CtyIOmP7yiuKL83XDyykL2aCJjV+wwLHgSoLhzkYvMWaMB+BQEaOcWRTyFxZcng20uxr0MKu/rNsVOdkCkCN8NWMGJWNaRx5yyunYWKPgZN2sD35aCZn5bia6RdYPZlnaECQJPxLi1GCiOZ9MNq/irWk9bLBLUwnYoWT0aahTnJN18b2M3dPzPV2zSphzRDAsTOjvBVQ=}
bot:
  automerge: true
conda_forge_output_validation: true
